### ISSUE TITLE
result

### ISSUE THREAD

**Issue by hustavo-newworld** [Badaben/socmec#1]
Yo ben
Apres qlq modifs dans les variables qui comportaient des coquilles (fierté d'y être arrivé tout seul !!), j'ai ca comme message d'erreur / sortie, sachant que je capte pas du tout comment récup les token pour insta / et facebook... need help la dessus.
Sinon ca semble ok !
------------------------------------------------------------
02/03/2020 09:40:59 [INFO] main  Started
02/03/2020 09:40:59 [INFO] main  Checking rss from http://cotesmeubles.fr/feed.php
02/03/2020 09:41:00 [INFO] main  New post found : Cuisine sur-mesure OSB
02/03/2020 09:41:00 [INFO] connectionpool  Starting new HTTPS connection (1): api.twitter.com
02/03/2020 09:41:00 [INFO] tweet  Connection Twitter OK
Fail to import moviepy. Need only for Video upload.
02/03/2020 09:41:00 [INFO] connectionpool  Starting new HTTPS connection (1): i.instagram.com
02/03/2020 09:41:00 [INFO] connectionpool  Resetting dropped connection: i.instagram.com
02/03/2020 09:41:03 [INFO] connectionpool  Resetting dropped connection: i.instagram.com
02/03/2020 09:41:03 [INFO] connectionpool  Resetting dropped connection: i.instagram.com
02/03/2020 09:41:03 [INFO] connectionpool  Resetting dropped connection: i.instagram.com
Request return 405 error!
{'message': '', 'status': 'fail'}
02/03/2020 09:41:04 [INFO] connectionpool  Resetting dropped connection: i.instagram.com
Request return 404 error!
02/03/2020 09:41:04 [INFO] connectionpool  Resetting dropped connection: i.instagram.com
Login success!

02/03/2020 09:41:04 [INFO] insta  Erreur 
02/03/2020 09:41:04 [INFO] connectionpool  Starting new HTTPS connection (1): graph.facebook.com
02/03/2020 09:41:05 [INFO] facebk  Echec de connection a facebook
02/03/2020 09:41:05 [INFO] pintrst  Echec de connection a pinterest
02/03/2020 09:41:05 [INFO] main  Formating post .....
02/03/2020 09:41:05 [INFO] main  Download image : http://cotesmeubles.fr/data/medias/blog/recap_blog.jpg
02/03/2020 09:41:05 [INFO] connectionpool  Starting new HTTP connection (1): cotesmeubles.fr
02/03/2020 09:41:05 [INFO] main  IMG filename : /home/pi/Documents/socmec/img/recap_blog.jpg
02/03/2020 09:41:05 [INFO] main  Img download complete
02/03/2020 09:41:05 [INFO] main  twitter post : {'status': 'Et zou \n\nCuisine sur-mesure OSB\nOSB mon amour !\nhttp://cotesmeubles.fr/index.php?article15/cuisine-sur-mesure-osb\n hast_tail\n#pornuiserie'}
02/03/2020 09:41:05 [INFO] main  Instagram post : {'photo_path': '/home/pi/Documents/socmec/img/recap_blog.jpg', 'caption': 'Et paf\nCuisine sur-mesure OSB\n#pornuiserie'}
02/03/2020 09:41:05 [INFO] main  Facebook post : {'message': '\nCuisine sur-mesure OSB\nOSB mon amour !\nhttp://cotesmeubles.fr/index.php?article15/cuisine-sur-mesure-osb\n', 'link': 'http://cotesmeubles.fr/index.php?article15/cuisine-sur-mesure-osb'}
02/03/2020 09:41:05 [INFO] main  Pinterest post : {'board': 'Default', 'note': 'Cuisine sur-mesure OSB', 'link': 'http://cotesmeubles.fr/index.php?article15/cuisine-sur-mesure-osb', 'image_url': 'http://cotesmeubles.fr/data/medias/blog/recap_blog.jpg'}
02/03/2020 09:41:05 [INFO] main  Formating done
02/03/2020 09:41:05 [INFO] main  Connection failed : t=True i=False f=False p=False
02/03/2020 09:41:05 [INFO] main  Failed to connect to at least one social service
            Please verify credentials configuration in config.json
            and rerun this script

**Comment by Badaben** [comment]
La branche instafix resoue le probleme de connection 

`07/03/2020 19:24:38 [INFO] insta  Connection a Instagram Ok 
07/03/2020 19:24:39 [INFO] connectionpool  Starting new HTTPS connection (1): graph.facebook.com
07/03/2020 19:24:39 [INFO] facebk  Echec de connection a facebook
07/03/2020 19:24:39 [INFO] pintrst  Echec de connection a [pinterest`
](https://github.com/Badaben/socmec/tree/instafix)
