### ISSUE TITLE
facebook

### ISSUE THREAD

**Issue by ecutsa** [Badaben/socmec#3]
salut
ca marche toujours avec facebook pour toi ?

**Comment by Badaben** [comment]
[Le script implemente maintenant une gestion basique des token facebook](https://github.com/Badaben/socmec/commit/14b476d1ee3c444b3872548db188bb0f40ed841f) 


[et la generation d'un fichier vide](https://github.com/Badaben/socmec/commit/fa8b37dc4f3ce9c2a49779c18629a8c07a2d85b3)

**Comment by Badaben** [comment]
Issue closed
